### PR TITLE
Login

### PR DESCRIPTION
**Pull request by fvilers**

### CODE REVIEW

**Comment by guerinsylvain** [comment]
until now, I encounter many errors when typing "npm install":
- incorrect version of python
- missing windows  8.1 SDK
etc...
I am working on it...

**Comment by fvilers** [comment]
Indeed, the registration system hash the password using [BCrypt](https://www.npmjs.com/package/bcrypt), it's a package that must be compiled natively. As such, you must have [some tools preinstalled](https://github.com/nodejs/node-gyp).

**Comment by guerinsylvain** [comment]
when the account registration succeeds, would it be possible to automatically perform a login ?

**Comment by fvilers** [comment]
Let's create another card and PR for this suggestion.

**Review by guerinsylvain — APPROVED** [review]

**Pull request merged**
